name: Distribute Debug Build

on:
  push:
    branches:
      - main  # ganti jika perlu

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Bundler & dependencies
        run: |
          gem install bundler
          bundle install

      - name: Decode google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > app/google-services.json

      - name: Decrypt .env.enc to .env
        run: |
          openssl aes-256-cbc -pbkdf2 -d -in fastlane/.env.enc -out fastlane/.env.tmp -pass pass:${{ secrets.MY_SALT }}

      - name: Run Android Linter
        run: ./gradlew lintDebug
        continue-on-error: true

      - name: Upload Lint HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html

      - name: Run Fastlane (build and upload debug)
        run: bundle exec fastlane android build_debug key:${{ secrets.MY_SALT }}

      - name: Clean decrypted .env
        run: rm -f .env.tmp