name: Distribute Debug Build

on:
  push:
    branches:
      - main  # ganti jika perlu

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Bundler & dependencies
        run: |
          gem install bundler
          bundle install

      - name: Decode google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > app/google-services.json

      - name: Decrypt .env.enc to .env
        env:
          FASTLANE_SECRET_KEY: ${{ secrets.MY_SALT }}
        run: |
          openssl aes-256-cbc -d -in .env.enc -out .env.tmp -pass pass:FASTLANE_SECRET_KEY

      - name: Run Fastlane (build and upload debug)
        env:
          FASTLANE_SECRET_KEY: ${{ secrets.MY_SALT }}
        run: bundle exec fastlane android build_debug key:$FASTLANE_SECRET_KEY

      - name: Clean decrypted .env
        run: rm -f .env.tmp