name: Distribute Debug Build

on:
  push:
    branches:
      - main  # ganti sesuai branch yang kamu mau

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'  # atau 3.x terbaru

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Decode google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > app/google-services.json

      - name: Set ENV for Firebase + Telegram
        run: |
          echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> .env
          echo "FIREBASE_CI_TOKEN=${{ secrets.FIREBASE_CI_TOKEN }}" >> .env
          echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> .env
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> .env

      - name: Run Fastlane (build and upload APK)
        run: bundle exec fastlane android build_debug
