name: Distribute Debug Build

on:
  push:
    branches:
      - main  # atau cabang lain yang kamu pakai

jobs:
  distribute-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Decode google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > app/google-services.json

      - name: Set Firebase token
        run: echo "FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}" >> $GITHUB_ENV

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK to Firebase App Distribution
        run: ./gradlew appDistributionUploadDebug
